

// State  - argument is not full application state,
// This is the part of the state that was generated by book reducer
export default function(state = null, action) {
    if (!action) {
        console.log('book reducer received an undefined action. doing nothing..');
        return state;
    }

    switch(action.type) {
        
        // Our action
        case 'BOOK_SELECTED':
            return action.payload;
        
        default:
            return state;
    }

    return state;
}